#!/bin/bash

# Use and run https://github.com/ssllabs/ssllabs-scan and save the results to a file

CHECK=ssllabs
LOG_DIR=/var/cache/bloonix
ERROR_LOG=$LOG_DIR/$CHECK.err.log

[ -d $LOG_DIR ] || mkdir -p $LOG_DIR

# host is required, report the error to a generic error file.
if [ $# -eq 0 ]; then
    echo "$(date '+%Y-%m-%d %H:%M:%S') $0 called with NO arguments!" > $ERROR_LOG
    exit 1;
fi

#cmd=$(which echo)              # Testing rest of code without ssllabs-scan
cmd=$(which ssllabs-scan)
if [[ -z $cmd ]]; then
    echo "$(date '+%Y-%m-%d %H:%M:%S') Cannot find 'ssllabs-scan' command!" > $ERROR_LOG
    exit 1
fi

HOST="$1"
RESULTS="$LOG_DIR/${CHECK}_$HOST.json"
SCRATCH=$(mktemp --tmpdir=$LOG_DIR -t .tmp.$CHECK.XXXXXXXXXX)

# Cleanup even when interrupted; leave no temp files behind.
function finish {
    rm "$SCRATCH" 2>/dev/null
}
trap finish EXIT

$cmd "$HOST" > "$SCRATCH" && mv "$SCRATCH" "$RESULTS" && rm "$ERROR_LOG" 2>/dev/null
