#!/bin/bash
#
# Use and run https://github.com/ssllabs/ssllabs-scan and save the results to a file

ssllabs_executable="/usr/local/sbin/ssllabs-scan"

target_url="$1"
target_url_filenamed="$(echo $target_url | sed -e 's@^http://@@g' -e 's@https://@@g' -e 's@/$@@g' -e 's@/@_@g' )"
result_file="/var/cache/bloonix/ssllabs_${target_url_filenamed}.json"

mkdir -p /var/cache/bloonix


if [[ -z $target_url ]]; then
    echo "Please specify the full URL to check (https://www.example.com), aborting!"
    exit 1
fi

$ssllabs_executable "$target_url" > "$result_file"
