#!/bin/bash
#
# Check the size of a directory and write the output to a file for bloonix-agent


target_dir="$2"
result_file="/var/cache/bloonix/du_${1}.txt"
mkdir -p /var/cache/bloonix

if [[ -z $target_dir ]]; then
    echo "Please specify the full path to the directory to check, aborting!"
    exit 1
fi


dir_size_bytes="$(du -sx $target_dir 2>/dev/null | awk '{print $1}')"
dir_inodes="$(find $target_dir | wc -l 2>/dev/null)"


echo "{
  size: $dir_size_bytes,
  inodes: $dir_inodes
}" > "$result_file"
